### ISSUE TITLE
Discouraging strangers from jumping into my tables

### ISSUE THREAD

**Issue by mavit** [pocc/bga_discord#19]
Itʼs common on Board Game Arena that, once a table is opened (either deliberately or accidentally), strangers will immediately join the table.  This is frustrating if you were intending to set up a private game for friends, but forgot to restrict the table properly or made some other mistake.

The bot should do what it can to help this happen less often.  Ideas: 
- Iʼve [hacked](https://github.com/mavit/bga_discord/commit/0b15351ccb7b75d736a64dc2e52ab04865d03d87) my local copy of the bot to restrict tables to my BGA group by default.  This works for me, but doesnʼt seem obviously straightforward to generalise.
- If we put some descriptive information into the presentation field, maybe strangers will be less likely to jump in?

**Comment by pocc** [comment]
I feel like the easiest solution here is to add  `restrictgroup:myfriends` to your command.

Long-term, there should be a way to set default options for a discord server.

**Comment by pocc** [comment]
Going to close this because it's possible to set a custom restrictgroup now. Please reopen if you don't think this fixes.
