### ISSUE TITLE
Non-interactive setup no-longer works

### ISSUE THREAD

**Issue by mavit** [pocc/bga_discord#30]
Say `!setup username password` or `!bga setup username password` in a direct message to the bot or in a channel on which it's listening.  The bot responds with `Tell <@!234561564697559041> to fix his bga bot` and the following appears in the log:

```
Traceback (most recent call last):
  File "./src/main.py", line 66, in on_message
    await trigger_bga_action(message, args)
  File "./src/main.py", line 94, in trigger_bga_action
    bga_user, bga_passwd = args[1], args[2]
IndexError: list index out of range
```

**Comment by pocc** [comment]
This has been fixed in my testing as of 247bf03. Feel free to reopen if you find differently.
