### ISSUE TITLE
Interactive !setup of username doesn't terminate

### ISSUE THREAD

**Issue by mavit** [pocc/bga_discord#31]
Say `!setup` then `1` then `username` to the bot.  The bot stores your username but doesn't respond.  Further messages continue to change the stored username.

**Comment by mavit** [comment]
There's the same issue when trying to set the password.

**Comment by pocc** [comment]
This is a good point. The contexts state variable will now reset the context for that user so they should be able to set other things.

It might make sense to say something like "$var saved successfully!"
