### ISSUE TITLE
Should files end with a newline character?

### ISSUE THREAD

**Issue by mavit** [pocc/bga_discord#8]
I find that files in this project tend not to end in a newline, whereas my text editor is keen that files should end in a newline.  This causes messy diffs.

The [EditorConfig](https://editorconfig.org/) standard is supported by many text editors, and could be used to tell them to behave in the way preferred by this project's maintainer.

**Comment by pocc** [comment]
You are right.

Per [PEP8](https://pep8.readthedocs.io/en/release-1.7.x/intro.html) code W292, this is standard in the Python language (and text files traditionally). I think a better way to do this is run pre-commit over this with a couple linters and setup travis to run that on commit.

I'll be able to expand on this more later.
